version: '3'
services:
  nginx_static: 
    image: nginx
    container_name: nginx_static
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "${DOCKER_STATIC_HOSTING}:/var/www/static"
    ports:
      - "${PORT}:80"
    networks:
      - proxy
    environment:
      VIRTUAL_HOST: ${SSL_DOMAIN}
      VIRTUAL_PORT: ${PORT}
      LETSENCRYPT_HOST: ${SSL_DOMAIN}

networks:
  proxy:
    external:
      name: ${NGINX_PROXY_NETWORK}
