version: '3'
services:
  nginx_static:
    image: nginx
    container_name: nginx_static
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "${DOCKER_STATIC_HOSTING}:/var/www/static"
    ports:
      - "${PORT}:80"
    networks:
      - https

networks:
  https:
    external:
      name: ${HTTPS_NETWORK}
